from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.config import Settings
from app.models import DetectionRecord, Incident, IncidentSeverity, IncidentStatus, SecurityEvent
from app.security.detection import DetectionEvent, RuleMatch, active_rules, detect
from app.security.parser import ParsedLogRecord


@dataclass(frozen=True)
class StoredDetection:
    record: DetectionRecord
    incident_id: int
    match: RuleMatch


def _severity_rank(severity: IncidentSeverity) -> int:
    return {
        IncidentSeverity.LOW: 0,
        IncidentSeverity.MEDIUM: 1,
        IncidentSeverity.HIGH: 2,
        IncidentSeverity.CRITICAL: 3,
    }[severity]


def ingest_records(records: list[ParsedLogRecord], db: Session, settings: Settings) -> list[StoredDetection]:
    """Persist parsed evidence, evaluate rules, and create/group incidents atomically."""
    if not records:
        return []

    with db.begin():
        new_events = [
            SecurityEvent(
                incident_id=None,
                event_type=item.event_type,
                description=item.description,
                source_ip=item.source_ip,
                username=item.username,
                hostname=item.hostname,
                timestamp=item.timestamp,
                raw_log=item.raw_log,
            )
            for item in records
        ]
        db.add_all(new_events)
        db.flush()

        source_ips = {event.source_ip for event in new_events if event.source_ip}
        timed_records = [item.timestamp for item in records if item.timestamp is not None]
        if not source_ips or not timed_records:
            return []

        maximum_window = max(rule.window_seconds for rule in active_rules(settings))
        cutoff = min(timed_records) - timedelta(seconds=maximum_window)
        candidates = list(db.scalars(
            select(SecurityEvent).where(
                SecurityEvent.source_ip.in_(source_ips),
                SecurityEvent.timestamp.is_not(None),
                SecurityEvent.timestamp >= cutoff,
            )
        ).all())
        detection_events = [
            DetectionEvent(
                id=event.id,
                event_type=event.event_type,
                timestamp=event.timestamp,
                source_ip=event.source_ip,
                username=event.username,
                raw_log=event.raw_log,
            )
            for event in candidates
        ]
        matches = detect(detection_events, {event.id for event in new_events}, settings)
        candidate_by_id = {event.id: event for event in candidates}
        now = datetime.now(timezone.utc)
        group_cutoff = now - timedelta(seconds=settings.detection_grouping_window_seconds)
        stored: list[StoredDetection] = []

        for match in matches:
            incident = db.scalar(
                select(Incident)
                .where(
                    Incident.status == IncidentStatus.OPEN,
                    Incident.source_ip == match.source_ip,
                    Incident.created_at >= group_cutoff,
                    Incident.title.like("Detection:%"),
                )
                .order_by(Incident.created_at.desc(), Incident.id.desc())
                .with_for_update()
            )
            if incident is None:
                incident = Incident(
                    title=f"Detection: [{match.rule_id}] {match.name} from {match.source_ip}",
                    description=(
                        f"Automatically generated by deterministic detection.\n"
                        f"Detection rule: {match.rule_id} ({match.name})\n\n"
                        f"{match.description}"
                    ),
                    severity=match.severity,
                    status=IncidentStatus.OPEN,
                    source_ip=match.source_ip,
                )
                db.add(incident)
                db.flush()
            else:
                if f"Detection rule: {match.rule_id} " not in incident.description:
                    incident.description = (
                        f"{incident.description}\n\nDetection rule: {match.rule_id} ({match.name})\n"
                        f"{match.description}"
                    )
                if _severity_rank(match.severity) > _severity_rank(incident.severity):
                    incident.severity = match.severity

            matched_events = [candidate_by_id[event_id] for event_id in match.event_ids if event_id in candidate_by_id]
            for event in matched_events:
                if event.incident_id is None:
                    event.incident = incident
            db.flush()

            previous_record = db.scalar(
                select(DetectionRecord)
                .where(
                    DetectionRecord.rule_id == match.rule_id,
                    DetectionRecord.source_ip == match.source_ip,
                    DetectionRecord.incident_id == incident.id,
                    DetectionRecord.detected_at >= group_cutoff,
                )
                .order_by(DetectionRecord.detected_at.desc(), DetectionRecord.id.desc())
                .with_for_update()
            )
            if previous_record is None:
                detection_record = DetectionRecord(
                    rule_id=match.rule_id,
                    rule_name=match.name,
                    severity=match.severity,
                    description=match.description,
                    source_ip=match.source_ip,
                    incident_id=incident.id,
                    events=matched_events,
                )
                db.add(detection_record)
            else:
                detection_record = previous_record
                detection_record.description = match.description
                for event in matched_events:
                    if event not in detection_record.events:
                        detection_record.events.append(event)
            db.flush()
            stored.append(StoredDetection(detection_record, incident.id, match))

    return stored
