from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.schemas.verification import ResponseRecommendationInput, VerificationReportRead


class StrictOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")


class EvidenceStatement(StrictOutput):
    classification: Literal["observed_fact", "hypothesis"]
    text: str = Field(min_length=1, max_length=300)
    event_ids: list[int] = Field(min_length=1, max_length=5)
    source_ip: str | None = None
    username: str | None = None
    hostname: str | None = None
    timestamp: datetime | None = None
    successful_login: bool | None = None

    @model_validator(mode="after")
    def observed_fact_has_structured_anchor(self):
        if self.classification == "observed_fact" and all(value is None for value in (
            self.source_ip, self.username, self.hostname, self.timestamp, self.successful_login,
        )):
            raise ValueError("Observed facts require at least one structured evidence field.")
        return self


class CompactTextEvidence(StrictOutput):
    text: str = Field(min_length=1, max_length=300)
    event_ids: list[int] = Field(min_length=1, max_length=3)


class CompactInterpretation(StrictOutput):
    text: str = Field(min_length=1, max_length=250)
    event_ids: list[int] = Field(min_length=1, max_length=3)


class CompactRecommendation(StrictOutput):
    text: str = Field(min_length=1, max_length=250)
    action_type: Literal["review_logs", "block_source_ip", "rate_limit_source_ip", "disable_account", "reset_password", "other"]
    event_ids: list[int] = Field(min_length=1, max_length=3)


class LLMInvestigationOutput(StrictOutput):
    """Only concise interpretation fields generated by the local model."""
    summary: CompactTextEvidence
    findings: list[CompactInterpretation] = Field(default_factory=list, max_length=2)
    attack_reconstruction: list[CompactInterpretation] = Field(default_factory=list, max_length=2)
    impact_assessment: list[CompactInterpretation] = Field(default_factory=list, max_length=2)
    response_recommendations: list[CompactRecommendation] = Field(default_factory=list, max_length=3)


class NarrativeSection(StrictOutput):
    summary: str = Field(min_length=1, max_length=500)
    event_ids: list[int] = Field(default_factory=list, max_length=10)
    uncertainty: str = Field(min_length=1, max_length=120)


class ImpactAssessment(StrictOutput):
    observed: list[EvidenceStatement] = Field(default_factory=list, max_length=3)
    potential: list[EvidenceStatement] = Field(default_factory=list, max_length=3)


class RiskAssessment(StrictOutput):
    level: Literal["low", "medium", "high", "critical", "unknown"]
    rationale: str = Field(min_length=1, max_length=240)
    event_ids: list[int] = Field(default_factory=list, max_length=5)
    uncertainty: str = Field(min_length=1, max_length=120)


class RecommendationDraft(StrictOutput):
    text: str = Field(min_length=1, max_length=250)
    action_type: Literal["review_logs", "block_source_ip", "rate_limit_source_ip", "disable_account", "reset_password", "other"]
    event_ids: list[int] = Field(min_length=1, max_length=5)
    source_ip: str | None = None
    username: str | None = None


class InvestigationAnalysis(StrictOutput):
    summary: str | None = Field(default=None, max_length=300)
    summary_event_ids: list[int] = Field(default_factory=list, max_length=3)
    triage: NarrativeSection
    findings: list[EvidenceStatement] = Field(default_factory=list, max_length=5)
    attack_reconstruction: NarrativeSection
    impact_assessment: ImpactAssessment
    risk_assessment: RiskAssessment
    response_recommendations: list[RecommendationDraft] = Field(default_factory=list, max_length=5)


class PipelineModuleStatus(BaseModel):
    module: str
    responsibility: str
    method: Literal["deterministic", "ollama", "independent_deterministic"]
    status: Literal["completed", "unavailable", "failed"]


class InvestigationRunRead(BaseModel):
    status: Literal["completed", "unavailable", "failed"]
    provider: Literal["ollama"] = "ollama"
    model: str
    inference_used: bool
    investigation_result_id: int | None = None
    generated_at: datetime | None = None
    analysis: InvestigationAnalysis | None = None
    verification: VerificationReportRead | None = None
    modules: list[PipelineModuleStatus] = Field(default_factory=list)
    error_message: str | None = None


class InvestigationRequest(BaseModel):
    refresh: bool = True
